### ISSUE TITLE
haproxy-conf could be awesome!

### ISSUE THREAD

**Issue by InAnimaTe** [yaronr/dockerfile#2]
Your haproxy-conf container seems to be probably the most powerful one out there.

I've spent a bit looking at everything available and most of them don't allow many configuration options outside of a basic mapping hostname -> backend IP.

Your's looks like it allows basic tcp proxies as well, which is magnificent for people that just want to pass-through ssl/tls, like me:)

A few things that could make this the definitive proxy container:
- More documentation. Just sit down and do it. Hell I'll help a bit!
- Allow specifying more options to haproxy i.e. http -> https redirection, forwardfor, etc.. Here's [another](https://github.com/michaelcontento/docker-haproxy-etcd) container that provides some of those extras.
- Consider combining in [registrator](https://github.com/progrium/registrator) or [docker-gen/docker-register](https://github.com/jwilder/docker-register) to enable watching the docker event stream to automatically handle adding entries for a given service. I have some idea's on this if you'd like to chat more (inanimate on freenode)
- Make a separate repo for haproxy-confd. It will make it easier for people to find and allow its own issue and wiki pages.

Overall, I'd love to see more work put into this container! It could really be a beastly solution to reverse proxying services running on a coreos cluster, which is something that has been a bit difficult for many.

**Comment by yaronr** [comment]
Ciao Mario

Take a look at yaronr/discovery. It’s still work in progress, but it’s working well and I’m using it in 'production’.
The is the next generation of discovery I’m working on.
It’s based on apache velocity for the templateing, which is much simpler / stronger / more common than golang’s {{}{{{{}}}}}{}} templates.. :)

And it supports Apache Mesos/Marathon at the same time as etcd.
In the future I’ll open source it, and anyone could add their own provider. It’s in Java, so again - simpler, and more accessible to 99% of the people.
