### ISSUE TITLE
mesos-master

### ISSUE THREAD

**Issue by rogaha** [yaronr/dockerfile#3]
Hi @yaronr, 

I saw your example of the mesos-master container on docker hub(https://registry.hub.docker.com/u/yaronr/mesos/). I was wondering if you manage to start the container on bridge mode and still access the mesos UI from the host's IP (external):5050 ? 

Thanks in advance.

**Comment by yaronr** [comment]
Hi @rogaha 
Thanks for using my code :)

The answer is yes, I have full use of the UI (but I'm not 100% sure I understand the question)
By 'bridge mode' - do you mean using docker -b ? (I don't think so)
Are you using it with Weave as well, or with the default Docker networking?

To access the UI (port 5050) you need to expose it to the host (either with a specific port, or random).

Let me know, I'll be happy to help.

**Comment by rogaha** [comment]
Hi @yaronr, 

Thanks for the prompt reply. What I mean by 'bridge mode' is --net="bridge", so I'm using weave-dns to give names to the nodes across multiple data-centers. But I encountered some issues on the way, maybe you have faced them as well:
- When I start mesos-master with bridge-mode, I'm not able to access it using the external's IP port 5050. I'm able to access using the external IP if I run docker in host-mode (--net="host"). 
  <pre> 
  5a0f49905b6c        rogaha/mesos-base:latest   "/entrypoint.sh meso   4 minutes ago        Up 4 minutes        0.0.0.0:5050->5050/tcp
  9ad353095d7b        rogaha/marathon:latest     "/usr/local/bin/mara   4 minutes ago        Up 4 minutes        0.0.0.0:8080->8080/tcp                                                   rgh_marathon3
  -----
  root@rogaha3:~# curl -I 104.236.102.22:8080
  HTTP/1.1 200 OK
  Content-Type: text/html
  Content-Length: 507
  Cache-Control: max-age=0, must-revalidate
  Last-Modified: Tue, 09 Dec 2014 18:54:56 GMT
  Server: Jetty(8.y.z-SNAPSHOT)
  -----
  root@rogaha3:~#
  root@rogaha3:~# curl 104.236.102.22:5050
  curl: (7) Failed to connect to 104.236.102.22 port 5050: Connection refused
  root@rogaha3:~#
  </pre>
- When I run mesos-master using your instructions (without calling `weave run`) we don't create the network interface inside de container (ethwe) that gives me the access to the network created by weavedns. Am I missing something?
- Did you manage to expose the ports to access the slave/tasks logs from the mesos UI?

Thanks in advance and congrats for your great work!

**Comment by yaronr** [comment]
Here's the thing. I run the mesos master 'only on the weave network', meaning - mesos slaves use the weave network to connect to it (that's the whole point). Theoretically I think you can expose that port as well using -p, but if I recall correctly weave had an issue with that (routing problem I think).

I guess that you want to connect to the mesos master for monitoring & admin, using a browser.
There, my solution is quite different. I use a VPN to connect to the weave network :)

Once you get down to the basic things that are time tested and work great, like network - things start to become simple & reliable. (and secure, in this case... )
